---
apiVersion: v1
kind: Service
metadata:
  name: test
  annotations:
    werf.io/no-activity-timeout: "5s"
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
spec:
  selector:
    app: lesikovtest3
  ports:
  - port: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lesikovtest3-demo
spec:
  selector:
    matchLabels:
      app: lesikovtest3
  template:
    metadata:
      labels:
        app: lesikovtest3
    spec:
      containers:
      - image: nginx
        name: demo
